# Generated by Django 2.1.3 on 2018-11-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('matches', models.IntegerField()),
            ],
        ),
    ]
