# Generated by Django 2.1.3 on 2018-11-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
